@baseURL = http://localhost:3000/

### Login
POST {{baseURL}}api/users/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456789"
}

### Register
POST {{baseURL}}api/users/register
Content-Type: application/json

{
    "name": "batman",
    "email": "test2@gmail.com",
    "password": "123456789",
    "password2": "123456789"
}